### ISSUE TITLE
Prediction using GPU

### ISSUE THREAD

**Issue by sougata-ub** [davidalami/ConveRT#2]
Is it possible to leverage GPU for the predictions?

**Comment by davidalami** [comment]
Hello and thank you for the question!
Yes, sure it is possible, just `pip install tensorflow-gpu==1.14.0` in current environment with installed ConveRT. In case both are installed, tensorflow will place operations on GPU by default unless instructed not to, so you should be good to go.

**Comment by sougata-ub** [comment]
Thank you.
